[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "neurosnap"
version = "0.0.12"
authors = [
  {name="Keaun Amani"},
]
description = "Collection of useful bioinformatic functions and tools for various computational biology pipelines."
license = {file = "LICENSE"}
readme = "README.md"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: CC BY 4.0 License",
  "Operating System :: OS Independent",
  "Development Status :: 3 - Alpha",
]
requires-python = ">=3.8"
dependencies = [
  "requests>2",
  "numpy>1.0.0",
  "biopython",
  "biotite",
  "openbabel-wheel",
  "rdkit-pypi",
]

[project.urls]
Homepage = "https://github.com/KeaunAmani/neurosnap"
Issues = "https://github.com/KeaunAmani/neurosnap/issues"